[cerebrium.deployment]
name = "mtailor-assessment"
python_version = "3.10"
disable_auth = false
include = ['./*', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 1.0
memory = 4.0
compute = "CPU"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "docker/Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

